### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by the21st** [ricksbrown/mboxtract#2]
Hi, thanks for creating mboxtract!

I tried to use it on my gmail takeout mbox file but after several files, it failed with:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'attachments/2018-05-10/documents/EUR20180430112893-PoA_5847.pdf'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:687:12)
    at WriteStream.emit (events.js:182:13)
    at fs.open (internal/fs/streams.js:250:12)
    at FSReqWrap.oncomplete (fs.js:145:20)
```

Thanks for any help.

**Comment by ricksbrown** [comment]
oh sorry i only just noticed this issue, i'll check it out, thanks for letting me know
