### ISSUE TITLE
punycode module is deprecated

### ISSUE THREAD

**Issue by interferingpanda** [ricksbrown/mboxtract#4]
NodeJS v 21.1.0 on Mac OS X 14.1.1

```
❯ mboxtract --subdirs -o attachments VOIP.mbox
(node:97700) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/homebrew/lib/node_modules/mboxtract/node_modules/mailparser/lib/mail-parser.js:32
        this.errored = false;
                     ^

TypeError: Cannot set property errored of #<Readable> which has only a getter
    at new MailParser (/opt/homebrew/lib/node_modules/mboxtract/node_modules/mailparser/lib/mail-parser.js:32:22)
    at MboxStream.<anonymous> (/opt/homebrew/lib/node_modules/mboxtract/index.js:46:17)
    at MboxStream.emit (node:events:515:28)
    at SBMH.<anonymous> (/opt/homebrew/lib/node_modules/mboxtract/node_modules/node-mbox/src/mbox.js:100:16)
    at SBMH.emit (node:events:515:28)
    at SBMH._sbmh_feed (/opt/homebrew/lib/node_modules/mboxtract/node_modules/streamsearch/lib/sbmh.js:159:14)
    at SBMH.push (/opt/homebrew/lib/node_modules/mboxtract/node_modules/streamsearch/lib/sbmh.js:56:14)
    at MboxStream._transform (/opt/homebrew/lib/node_modules/mboxtract/node_modules/node-mbox/src/mbox.js:119:17)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:556:12)

Node.js v21.1.0
```

**Comment by ricksbrown** [comment]
Thanks 🙇‍♀️ 
This was resolved by PR #5
